# Generated by Django 5.0.6 on 2024-07-19 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(db_column='ID_CLIENTE', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.PositiveIntegerField()),
                ('email', models.CharField(max_length=30)),
                ('id_vehiculo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('id_conductor', models.AutoField(db_column='ID_CONDUCTOR', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('licencia', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gruas',
            fields=[
                ('id_grua', models.AutoField(db_column='ID_GRUAS', primary_key=True, serialize=False)),
                ('modelo', models.TextField()),
                ('capacidad', models.PositiveIntegerField()),
                ('estado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(db_column='ID_EMPRESA', primary_key=True, serialize=False)),
                ('direccion_emp', models.CharField(max_length=50)),
                ('telefono', models.PositiveIntegerField()),
                ('mail', models.CharField(max_length=20)),
                ('encargado', models.TextField()),
                ('id_servicio', models.TextField()),
                ('conductor', models.ForeignKey(db_column='CONDUCTORES_ID_CONDUCTOR', on_delete=django.db.models.deletion.CASCADE, to='cliente.conductores')),
                ('grua', models.ForeignKey(db_column='Grúas_ID_GRUAS', on_delete=django.db.models.deletion.CASCADE, to='cliente.gruas')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_solicitud', models.AutoField(db_column='ID_SOLICITUD', primary_key=True, serialize=False)),
                ('fecha_solicitud', models.CharField(max_length=10)),
                ('estado', models.TextField()),
                ('ubi_origen', models.TextField()),
                ('ubi_final', models.TextField()),
                ('cliente', models.ForeignKey(db_column='CLIENTES_ID_CLIENTE', on_delete=django.db.models.deletion.CASCADE, to='cliente.clientes')),
                ('conductor', models.ForeignKey(db_column='CONDUCTORES_ID_CONDUCTOR', on_delete=django.db.models.deletion.CASCADE, to='cliente.conductores')),
                ('grua', models.ForeignKey(db_column='Grúas_ID_GRUAS', on_delete=django.db.models.deletion.CASCADE, to='cliente.gruas')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.PositiveIntegerField(db_column='ID_UBICACION', primary_key=True, serialize=False)),
                ('latitud', models.PositiveIntegerField()),
                ('longitud', models.PositiveIntegerField()),
                ('marca_tiempo', models.PositiveIntegerField()),
                ('grua', models.ForeignKey(db_column='Grúas_ID_GRUAS', on_delete=django.db.models.deletion.CASCADE, to='cliente.gruas')),
            ],
        ),
    ]
